Blueline_Methods_welcome:
    path: /
    defaults: { _controller: BluelineMethodsBundle:Methods:welcome }

Blueline_Methods_view:
    path: /view/{url}.{_format}
    defaults: { _controller: BluelineMethodsBundle:Methods:view, _format: html }
    requirements:
        _format: html|json|png

Blueline_Methods_custom_view:
    path: /view.{_format}
    defaults: { _controller: BluelineMethodsBundle:Methods:viewCustom, _format: html }
    requirements:
        _format: html|json|png

Blueline_Methods_print:
    path: /print
    defaults: { _controller: BluelineMethodsBundle:Methods:print, _format: html }
    requirements:
        _format: html|json|png

Blueline_Methods_export:
    path: /export.{_format}
    defaults: { _controller: BluelineMethodsBundle:Methods:export }
    requirements:
        _format: html|png|pdf

Blueline_Methods_search:
    path: /search.{_format}
    defaults: { _controller: BluelineMethodsBundle:Methods:search, _format: html }
    requirements:
        _format: html|json

Blueline_Methods_sitemap:
    path: /sitemap_{page}.{_format}
    defaults: { _controller: BluelineMethodsBundle:Methods:sitemap }
    requirements:
        page: \d+
        _format: xml
