Blueline_Methods_welcome:
    pattern:  /
    defaults: { _controller: BluelineMethodsBundle:Methods:welcome }

Blueline_Methods_view:
    pattern: /view/{title}.{_format}
    defaults: { _controller: BluelineMethodsBundle:Methods:view, _format: html }
    requirements:
        title: ^(?(?=.*\.(html|txt|json|xml)$).*(?=\.)|.*$)
        _format: html|txt|json|xml

Blueline_Methods_search:
    pattern:  /search.{_format}
    defaults: { _controller: BluelineMethodsBundle:Methods:search, _format: html }
    requirements:
        _format: html|txt|json|atom

Blueline_Methods_sitemap:
    pattern:  sitemap.{_format}
    defaults: { _controller: BluelineMethodsBundle:Methods:sitemap }
    requirements:
        _format: xml
