Blueline\MethodsBundle\Entity\Method:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: url
    properties:
        stage:
            - GreaterThanOrEqual:
                value: 4
        lengthOfLead:
            - GreaterThanOrEqual:
                value: 1
        numberOfHunts:
            - GreaterThanOrEqual:
                value: 0
        ruleOffs:
            - Regex: "/^-?\d+:-?\d+$/"