doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.default
                auto_mapping: true
                mappings:
                    Blueline:
                        is_bundle: false
                        type: yml
                        dir: '%kernel.project_dir%/config/doctrine'
                        prefix: 'Blueline\Entity'
                        alias: Blueline
                dql:
                    string_functions:
                        regexp:
                            Blueline\Doctrine\Regexp
                        levenshtein:
                            Blueline\Doctrine\Levenshtein
                        levenshtein_ratio:
                            Blueline\Doctrine\LevenshteinRatio

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
