#!/bin/bash

dWhich=`which "$0"`
d=`dirname "$dWhich"`

# Update the localStorage clear parameter in history.js
sed -i -e"s/clearBefore = new Date(.*$/clearBefore = new Date( `date "+%Y, %-m, %-d, %-H, %-M"` );/" "$d/../../web/scripts/history.js"

# Execute RequireJS builder
node "$d/helpers/r.js" -o app.build.js

# JS
# Copy to scripts.built
rm -rf "$d/../../web/scripts.built"
mv "$d/../../www-build/scripts" "$d/../../web/scripts.built"


# Remove www-build directory
rm -rf "$d/../../www-build"
