#!/bin/bash

dWhich=`which "$0"`
d=`dirname "$dWhich"`

# Execute RequireJS builder
"$d/helpers/requirejs/build/build.sh" app.build.js

# CSS
# Remove unneeded files
rm -rf "$d/../../www-build/styles/ui"
rm -rf "$d/../../www-build/styles/helpers"
# GZip compiled CSS
find "$d/../../www-build/" -type f -name "*.css" -print | parallel -j +0 "gzip -9c {} > {}.gz"
# Copy to styles.built
rm -rf "$d/../../www/styles.built"
mv "$d/../../www-build/styles" "$d/../../www/styles.built"

# JS
# Remove unneeded files
rm "$d/../../www-build/scripts/require.js"
rm -rf "$d/../../www-build/scripts/helpers"
rm -rf "$d/../../www-build/scripts/plugins"
rm "$d/../../www-build/scripts/ui/Content.js"
rm "$d/../../www-build/scripts/ui/Header.js"
rm "$d/../../www-build/scripts/ui/Page.js"
rm "$d/../../www-build/scripts/ui/TabBar.js"
# GZip compressed JS
find "$d/../../www-build/" -type f -name "*.js" -print | parallel -j +0 "gzip -9c {} > {}.gz"
# Copy to scripts.built
rm -rf "$d/../../www/scripts.built"
mv "$d/../../www-build/scripts" "$d/../../www/scripts.built"


# Remove www-build directory
rm -rf "$d/../../www-build"