#!/bin/bash

dWhich=`which "$0"`
d=`dirname "$dWhich"`

# Remove old and unneeded files
rm -rf "$d/../../web/scripts.built"
rm -rf "$d/../../web/bundles"
rm -rf "$d/../../web/css"

# Update the clear parameter in ContentCache.js
sed -i -e"s/var clearBefore = (new Date(.*$/var clearBefore = (new Date( `date "+%Y, %-m-1, %-d"` ).toDateString());/" "$d/../../web/scripts/helpers/ContentCache.js"

# Execute RequireJS builder
node "$d/helpers/r.js" -o "$d/app.build.js"

# Reset ContentCache.js
git checkout -- "$d/../../web/scripts/helpers/ContentCache.js"

# Run the Closure compiler on all scripts (This is so slow it's painful)
#for f in $(find "$d/../../web/scripts.built" -name "*.js"); do
#	java -jar "$d/../../app/Resources/java/compiler.jar" --charset "UTF-8" --compilation_level SIMPLE_OPTIMIZATIONS --js "$f"
#done

# Dump production assets from Symfony
"$d/../../app/console" assetic:dump --env=prod --no-debug

# Update web_updated parameter
if [[ ! -h "$d/../../app/config/parameters.ini" ]]
then
	sed -i -e"s/    web_update=.*/    web_update=\"`date --rfc-3339=seconds`\"/" "$d/../../app/config/parameters.ini"
fi
