#!/bin/bash

dWhich=`which "$0"`
d=`dirname "$dWhich"`

top=$d/../..

# Removes files that are unnecessary for production from the source tree

rm -rf "$top/docs"
rm -rf "$top/tests"
rm -rf "$top/resources"
rm -rf "$top/.git"
rm "$top/.gitignore"
rm "$top/libraries/parsecsv.lib.php"
rm "$top/libraries/phpcoord.php"

echo "Cleaned unneeded files"
