BluelinePagesBundle:
    resource: "@BluelinePagesBundle/Resources/config/routing_pages.yml"
    prefix:   /

BluelineAssociationsBundle:
    resource: "@BluelineAssociationsBundle/Resources/config/routing_associations.yml"
    prefix:   /associations/

BluelineMethodsBundle:
    resource: "@BluelineMethodsBundle/Resources/config/routing_methods.yml"
    prefix:   /methods/

BluelineTowersBundle:
    resource: "@BluelineTowersBundle/Resources/config/routing_towers.yml"
    prefix:   /towers/

Blueline_resource:
    pattern:  /{page}.{_format}
    defaults: { _controller: BluelineBundle:Default:resource }
    requirements:
        page: robots|humans|site|sitemap|sitemap_root
        _format: txt|xml|manifest

Blueline_favicon:
    pattern:  /favicon.{_format}
    defaults: { _controller: BluelineBundle:Asset:favicon }
    requirements:
        _format: ico|png|bmp|svg

Blueline_iOS_icon:
    pattern:  /apple-touch-icon-{size}.{_format}
    defaults: { _controller: BluelineBundle:Asset:iOS_icon }
    requirements:
        size: 57x57|72x72|76x76|114x114|120x120|144x144|152x152
        _format: png

Blueline_image:
    pattern:  /images/{image}.{_format}
    defaults: { _controller: BluelineBundle:Asset:image }
    requirements:
        image: external|search|select|loading|more|welcome_associations|welcome_methods|welcome_towers
        _format: png|jpg|bmp|gif|svg

Blueline_font:
    pattern:  /fonts/{font}.{_format}
    defaults: { _controller: BluelineBundle:Asset:font }
    requirements:
        font: Blueline
        _format: woff
