Blueline_welcome:
    path: /
    defaults: { _controller: BluelineBundle:Default:page, page: 'welcome' }

Blueline_manifest:
    path: /site.{_format}
    defaults: { _controller: BluelineBundle:Default:manifest }
    requirements:
        _format: manifest

BluelineMethodsBundle:
    resource: "@BluelineMethodsBundle/Resources/config/routing_methods.yml"
    prefix:   /methods/

BluelineTowersBundle:
    resource: "@BluelineTowersBundle/Resources/config/routing_towers.yml"
    prefix:   /towers/

BluelineAssociationsBundle:
    resource: "@BluelineAssociationsBundle/Resources/config/routing_associations.yml"
    prefix:   /associations/

Blueline_Pages_view:
    path: /{page}.{_format}
    defaults: { _controller: BluelineBundle:Default:page, _format: 'html' }
    requirements:
        page:    about|methods/tutorials|methods/notation
        _format: html

Blueline_resource:
    path: /{page}.{_format}
    defaults: { _controller: BluelineBundle:Default:resource }
    requirements:
        page: robots|humans|sitemap|sitemap_root|browserconfig|manifest
        _format: json|txt|xml

Blueline_Pages_redirect1:
    path: /copyright
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about
        permanent: true
Blueline_Pages_redirect2:
    path: /tutorials
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /methods/tutorials
        permanent: true

BluelineServicesBundle:
    resource: "@BluelineServicesBundle/Resources/config/routing_services.yml"
    prefix:   /services/


## Table exports
Blueline_Data_table:
    path: /data/{table}.{_format}
    defaults: { _controller: BluelineBundle:Data:table }
    requirements:
        table: associations|collections|methods|methods_collections|methods_similar|performances|towers|towers_associations|towers_oldpks
        _format: csv
