BluelineAssociationsBundle:
    resource: "@BluelineAssociationsBundle/Resources/config/routing_associations.yml"
    prefix:   /associations/

BluelineMethodsBundle:
    resource: "@BluelineMethodsBundle/Resources/config/routing_methods.yml"
    prefix:   /methods/

BluelineTowersBundle:
    resource: "@BluelineTowersBundle/Resources/config/routing_towers.yml"
    prefix:   /towers/

BluelineServicesBundle:
    resource: "@BluelineServicesBundle/Resources/config/routing_services.yml"
    prefix:   /services/


# Static pages
Blueline_welcome:
    path: /
    defaults: { _controller: BluelineBundle:Default:page, page: 'welcome' }

Blueline_Pages_view:
    path: /{page}.{_format}
    defaults: { _controller: BluelineBundle:Default:page, _format: 'html' }
    requirements:
        page:    about
        _format: html

Blueline_resource:
    path: /{page}.{_format}
    defaults: { _controller: BluelineBundle:Default:resource }
    requirements:
        page: robots|humans|sitemap|sitemap_root|browserconfig|manifest
        _format: json|txt|xml

Blueline_manifest:
    path: /site.{_format}
    defaults: { _controller: BluelineBundle:Default:manifest }
    requirements:
        _format: manifest

Blueline_Pages_copyright:
    path: /copyright
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about
        permanent: true


## Table exports
Blueline_Data_table:
    path: /data/{table}.{_format}
    defaults: { _controller: BluelineBundle:Data:table }
    requirements:
        table: associations|collections|methods|methods_collections|performances|towers|towers_associations|towers_oldpks
        _format: csv


## Image and other resources
Blueline_favicon:
    path: /favicon.{_format}
    defaults: { _controller: BluelineBundle:Asset:favicon }
    requirements:
        _format: ico|png|bmp|svg

Blueline_iOSicon:
    path: /appicon-{size}.{_format}
    defaults: { _controller: BluelineBundle:Asset:iOSicon }
    requirements:
        size: 57x57|72x72|76x76|96x96|114x114|120x120|144x144|152x152|180x180|192x192|196x196|256x256|384x384|512x512|768x768
        _format: png

Blueline_iOSstartup:
    path: /apple-startup-image-{ratio}-{size}.{_format}
    defaults: { _controller: BluelineBundle:Asset:iOSstartup }
    requirements:
        size: 640x1096|640x920|320x460|1536x2008|1496x2048|768x1004|748x1024
        ratio: 1|2
        _format: png

Blueline_image:
    path: /images/{image}.{_format}
    defaults: { _controller: BluelineBundle:Asset:image }
    requirements:
        image: database|external|search|select|loading|more|welcome_associations|welcome_methods|welcome_tutorials|welcome_towers|welcome_prover
        _format: png|jpg|bmp|gif|svg

Blueline_font:
    path: /fonts/{font}.{_format}
    defaults: { _controller: BluelineBundle:Asset:font }
    requirements:
        font: Blueline
        _format: woff|woff2
