#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
d="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

# Remove old file
rm -f "$d/levenshtein_ratio.so"

# Build new one
g++ -I /usr/include/mysql/ -o "$d/levenshtein_ratio.so" -fPIC -shared "$d/levenshtein_ratio.cc"

echo "Built UDFs"
echo "Install into MySQL plugin_dir: `echo "SHOW VARIABLES;" | mysql | grep "plugin_dir" | sed "s/plugin_dir[\t]//"`"
