Blueline\MethodsBundle\Entity\Method:
    type: entity
    repositoryClass: Blueline\MethodsBundle\Entity\MethodRepository
    table: methods
    id:
        title:
            type: string
            length: 255
    fields:
        url:
            type: string
            length: 255
        stage:
            type: smallint
        classification:
            type: string
            length: 31
            nullable: true
        nameMetaphone:
            type: string
            length: 255
            nullable: true
        notation:
            type: string
            length: 511
        notationExpanded:
            type: string
            length: 1023
        leadHeadCode:
            type: string
            length: 4
            nullable: true
        leadHead:
            type: string
            length: 31
        fchGroups:
            type: string
            length: 31
            nullable: true
        rwRef:
            type: string
            length: 255
            nullable: true
        bnRef:
            type: string
            length: 255
            nullable: true
        tdmmRef:
            type: integer
            nullable: true
        pmmRef:
            type: integer
            nullable: true
        lengthOfLead:
            type: integer
        numberOfHunts:
            type: smallint
        little:
            type: boolean
            nullable: true
        differential:
            type: boolean
            nullable: true
        plain:
            type: boolean
            nullable: true
        trebleDodging:
            type: boolean
            nullable: true
        palindromic:
            type: boolean
            nullable: true
        doubleSym:
            type: boolean
            nullable: true
        rotational:
            type: boolean
            nullable: true
        firstTowerbellPeal_date:
            type: date
            nullable: true
        firstTowerbellPeal_location:
            type: string
            length: 255
            nullable: true
        firstHandbellPeal_date:
            type: date
            nullable: true
        firstHandbellPeal_location:
            type: string
            length: 255
            nullable: true
        calls:
            type: text
            nullable: true
        ruleOffs:
            type: string
            length: 255
            nullable: true
    manyToOne:
        firstTowerbellPeal_tower:
            targetEntity: Blueline\TowersBundle\Entity\Tower
            inversedBy: firstPeals
            joinColumn:
                name: firstTowerbellPeal_doveid
                referencedColumnName: id
    oneToMany:
        renamed:
            targetEntity: Renamed
            mappedBy: method
        duplicate:
            targetEntity: Duplicate
            mappedBy: method
    manyToMany:
        collections:
            targetEntity: Collection
            inversedBy: methods
