Blueline\MethodsBundle\Entity\Renamed:
    type: entity
    table: methods_renamed
    id:
        id:
            type: string
            length: 32
    fields:
        title:
            type: string
            length: 255
        date:
            type: date
            nullable: true
        location:
            type: string
            length: 255
            nullable: true
        rwRef:
            type: string
            length: 255
    manyToOne:
        method:
            targetEntity: Method
            inversedBy: renamed
            joinColumn:
                name: actual_title
                referencedColumnName: title
                onDelete: CASCADE
