<?php

// Standard calls and rule offs for various methods which aren't in line with what would get generated by default
$method_extras_calls = [
    [
        'title' => 'Antelope Place Doubles',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '145.3.1',   'every' => 10, 'from' => -2, 'cover' => 3],
            'Single' => ['symbol' => 's', 'notation' => '145.3.123', 'every' => 10, 'from' => -2, 'cover' => 3],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 10, 'from' => 1],
    ],
    [
        'title' => 'Banana Doubles',
        'calls' => [
            'Lead-End Bob' => ['symbol' => '-', 'notation' => '125', 'every' => 8, 'from' => 0, 'cover' => 1],
            'Half-Lead Bob' => ['symbol' => 'h', 'notation' => '145', 'every' => 8, 'from' => -4, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 4, 'from' => 0],
    ],
    [
        'title' => 'Double Norwich Court Bob Caters',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '3',   'every' => 18, 'from' => 4, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '123', 'every' => 18, 'from' => 4, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 18, 'from' => 0],
    ],
    [
        'title' => 'Double Norwich Court Bob Cinques',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '3',   'every' => 22, 'from' => 4, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '123', 'every' => 22, 'from' => 4, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 22, 'from' => 0],
    ],
    [
        'title' => 'Erin Caters',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '7',   'every' => 6, 'from' => -5, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '789', 'every' => 6, 'from' => -5, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -5],
    ],
    [
        'title' => 'Erin Cinques',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '9',   'every' => 6, 'from' => -5, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '90E', 'every' => 6, 'from' => -5, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -5],
    ],
    [
        'title' => 'Erin Doubles',
        'calls' => [
            'Single' => ['symbol' => 's', 'notation' => '345', 'every' => 6, 'from' => -2, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -5],
    ],
    [
        'title' => 'Erin Octuples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => 'C',   'every' => 6, 'from' => -5, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => 'CDF', 'every' => 6, 'from' => -5, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -5],
    ],
    [
        'title' => 'Erin Septuples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => 'A',   'every' => 6, 'from' => -5, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => 'ABC', 'every' => 6, 'from' => -5, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -5],
    ],
    [
        'title' => 'Erin Sextuples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => 'E',   'every' => 6, 'from' => -5, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => 'ETA', 'every' => 6, 'from' => -5, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -5],
    ],
    [
        'title' => 'Erin Triples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '5',   'every' => 6, 'from' => -5, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '567', 'every' => 6, 'from' => -5, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -5],
    ],
    [
        'title' => 'Original Caters',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '7',   'every' => 2, 'from' => -1, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '789', 'every' => 2, 'from' => -1, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => 0],
    ],
    [
        'title' => 'Original Cinques',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '9',   'every' => 2, 'from' => -1, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '90E', 'every' => 2, 'from' => -1, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => 0],
    ],
    [
        'title' => 'Original Doubles',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '3',   'every' => 2, 'from' => -1, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '345', 'every' => 2, 'from' => -1, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => 0],
    ],
    [
        'title' => 'Original Triples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '5',   'every' => 2, 'from' => -1, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '567', 'every' => 2, 'from' => -1, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => 0],
    ],
    [
        'title' => 'Scientific Triples',
        'calls' => [
            'Red' => ['symbol' => '-', 'notation' => '3.7.3', 'every' => 30, 'from' => 6,  'cover' => 3],
            'Blue' => ['symbol' => '-', 'notation' => '3.7.3', 'every' => 30, 'from' => 15, 'cover' => 3],
            'Green' => ['symbol' => '-', 'notation' => '3.7.3', 'every' => 30, 'from' => 23, 'cover' => 3],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 30, 'from' => 0],
    ],
    [
        'title' => 'Shipway Minor',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '34',   'every' => 8, 'from' => 2, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '3456', 'every' => 8, 'from' => 2, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 8, 'from' => 2],
    ],
    [
        'title' => 'Shipway Major',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '36',   'every' => 8, 'from' => 2, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '3678', 'every' => 8, 'from' => 2, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 8, 'from' => 2],
    ],
    [
        'title' => 'Shipway Royal',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '38',   'every' => 8, 'from' => 2, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '3890', 'every' => 8, 'from' => 2, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 8, 'from' => 2],
    ],
    [
        'title' => 'Stedman Caters',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '7',   'every' => 6, 'from' => -3, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '789', 'every' => 6, 'from' => -3, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -3],
    ],
    [
        'title' => 'Stedman Cinques',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '9',   'every' => 6, 'from' => -3, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '90E', 'every' => 6, 'from' => -3, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -3],
    ],
    [
        'title' => 'Stedman Doubles',
        'calls' => [
            'Single' => ['symbol' => 's', 'notation' => '45', 'every' => 6, 'from' => 0, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -3],
    ],
    [
        'title' => 'Stedman Septuples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => 'A',   'every' => 6, 'from' => -3, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => 'ABC', 'every' => 6, 'from' => -3, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -3],
    ],
    [
        'title' => 'Stedman Sextuples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => 'E',   'every' => 6, 'from' => -3, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => 'ETA', 'every' => 6, 'from' => -3, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -3],
    ],
    [
        'title' => 'Stedman Triples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '5',   'every' => 6, 'from' => -3, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '567', 'every' => 6, 'from' => -3, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -3],
    ],
    [
        'title' => 'Stedman No.2 Jump Doubles',
        'calls' => [
            'Single' => ['symbol' => 's', 'notation' => '45', 'every' => 6, 'from' => 0, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => -3],
    ],
    [
        'title' => 'Stedman Jump Triples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '5',   'every' => 6, 'from' => 1, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '567', 'every' => 6, 'from' => 1, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 6, 'from' => 1],
    ],
    [
        'title' => 'Titanic Cinques',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '9',   'every' => 2, 'from' => -1, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '90E', 'every' => 2, 'from' => -1, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Titanic Doubles',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Titanic Triples',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '5',   'every' => 2, 'from' => -1, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '567', 'every' => 2, 'from' => -1, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Minimus',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Doubles',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Minor',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Triples',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Major',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Caters',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Royal',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Cinques',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Plain Hunt Maximus',
        'calls' => [],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 2, 'from' => -1],
    ],
    [
        'title' => 'Bristol Surprise Maximus',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '14',    'every' => 48, 'from' => 0, 'cover' => 1],
            'Single' => ['symbol' => 's', 'notation' => '1234',  'every' => 48, 'from' => 0, 'cover' => 1],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 48, 'from' => 0],
    ],
    [
        'title' => 'Solihull Bob Doubles',
        'calls' => [
            'Bob' => ['symbol' => '-', 'notation' => '5.1',    'every' => 10, 'from' => -1, 'cover' => 2],
            'Single' => ['symbol' => 's', 'notation' => '5.123',  'every' => 10, 'from' => -1, 'cover' => 2],
        ],
        'callingpositions' => [],
        'ruleoffs' => ['every' => 10, 'from' => 0],
    ],
];
