imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: [127.0.0.1]
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ "BluelineBundle" ]
    java: %java_path%
    filters:
        cssrewrite: ~
        less:
            node: %node_path%
            node_paths: [%node_modules_path%]
        closure:
            jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
    assets:
        jquery: %kernel.root_dir%/../vendor/components/jquery/jquery.js
        html5shiv: %kernel.root_dir%/../vendor/afarkas/html5shiv/dist/html5shiv.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    string_functions:
                        regexp:
                            Blueline\BluelineBundle\Doctrine\Extension\Regexp
                        concat_ws:
                            Blueline\BluelineBundle\Doctrine\Extension\ConcatWs
                        levenshtein_ratio:
                            Blueline\BluelineBundle\Doctrine\Extension\LevenshteinRatio
                    numeric_functions:
                        acos:
                            Blueline\BluelineBundle\Doctrine\Extension\Acos
                        cos:
                            Blueline\BluelineBundle\Doctrine\Extension\Cos
                        sin:
                            Blueline\BluelineBundle\Doctrine\Extension\Sin
                        radians:
                            Blueline\BluelineBundle\Doctrine\Extension\Radians

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# RequireJS Configuration
hearsay_require_js:
    base_dir: %kernel.root_dir%/Resources/public/js
    base_url: js
    paths:
        shared: '@BluelineBundle/Resources/public/js'
        methods: '@BluelineMethodsBundle/Resources/public/js'
        towers: '@BluelineTowersBundle/Resources/public/js'
        jquery: '%kernel.root_dir%/../vendor/components/jquery/jquery'
    optimizer:
        path: %kernel.root_dir%/Resources/js/r.js
        options:
            optmize: "uglify2"
            preserveLicenseComments: false
            useStrict: false

blueline:
    admin_email: %admin_email%
    analytics_code: %analytics_code%

    # The below parameters will automatically update themselves
    asset_update: %asset_update%