imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: [127.0.0.1]
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true
                dql:
                    string_functions:
                        regexp:
                            Blueline\BluelineBundle\Doctrine\Extension\Regexp
                        concat_ws:
                            Blueline\BluelineBundle\Doctrine\Extension\ConcatWs
                        levenshtein_ratio:
                            Blueline\BluelineBundle\Doctrine\Extension\LevenshteinRatio
                    numeric_functions:
                        acos:
                            Blueline\BluelineBundle\Doctrine\Extension\Acos
                        cos:
                            Blueline\BluelineBundle\Doctrine\Extension\Cos
                        sin:
                            Blueline\BluelineBundle\Doctrine\Extension\Sin
                        radians:
                            Blueline\BluelineBundle\Doctrine\Extension\Radians

blueline:
    admin_email: %admin_email%
    analytics_code: %analytics_code%

    # The below parameters will automatically update themselves
    asset_update: %asset_update%
    database_update: %database_update%