# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    #AppBundle\:
    #    resource: '../../src/AppBundle/*'
    project.doctrine_filesystem_cache:
        parent: doctrine_cache.abstract.file_system
        arguments: ['%kernel.cache_dir%/doctrine']
