#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
d="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd "$d"

# Download data
echo "Downloading method data..."
urls=( "https://cccbr.github.io/methods-library/xml/CCCBR_Plain.xml.zip"
       "https://cccbr.github.io/methods-library/xml/CCCBR_Surprise.xml.zip"
       "https://cccbr.github.io/methods-library/xml/CCCBR_Delight.xml.zip"
       "https://cccbr.github.io/methods-library/xml/CCCBR_Alliance.xml.zip"
       "https://cccbr.github.io/methods-library/xml/CCCBR_TreblePlace.xml.zip"
       "https://cccbr.github.io/methods-library/xml/CCCBR_Hybrid.xml.zip"
       "https://cccbr.github.io/methods-library/xml/CCCBR_TrebleBob.xml.zip"
       "https://cccbr.github.io/methods-library/xml/CCCBR_Principle.xml.zip"
       "https://cccbr.github.io/methods-library/xml/CCCBR_Differential.xml.zip"
       "http://www.methods.org.uk/supplement/provisionally-named/provisional-xml.zip"
       "http://methods.org.uk/other/renamed.htm"
       "http://methods.org.uk/other/duplicate.htm"
     )
for url in "${urls[@]}"; do
      curl --progress-bar --referer "http://www.methods.org.uk" --user-agent "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10" -o "$d/`basename "$url"`" "$url"
done

# Unzip all zip files
rm -f "CCCBR_*.xml"
unzip -qq -u -d "$d" -o "$d/*.zip"
find . -name "*.zip" -exec rm -rf "{}" \;
chmod +r *.xml

echo "Done"