<?php
namespace Blueline;
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
?>
<collection 
	xmlns="http://www.cccbr.org.uk/methods/schemas/2007/05/methods"
	xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	date="<?php echo date( 'Y-m-d' ); ?>">
	<collectionName>Search results for: <?php echo htmlspecialchars( $searchQuery ); ?></collectionName>
	<notes>Generated by Blueline using CCBR data</notes>
	<atom:link rel="search" type="application/opensearchdescription+xml" href="<?php echo Config::get( 'site.baseURL' ); ?>/services/opensearch/methods.xml"/>
	<opensearch:Query role="request" searchTerms="<?php echo htmlentities( $q ); ?>" />
	<opensearch:totalResults><?php echo $count; ?></opensearch:totalResults>
	<opensearch:startIndex><?php echo $limit['current']; ?></opensearch:startIndex>
	<methodSet>
<?php foreach( $methods as $method ) : ?>
		<method>
			<stage><?php echo $method->stage(); ?></stage>
			<notation><?php echo $method->notation(); ?></notation>
			<title><?php echo $method->title(); ?></title>
			<classification><?php echo $method->classification(); ?></classification>
		</method>
<?php endforeach; ?>
	</methodSet>
</collection>
