<?php
namespace Blueline;
use Pan\View;
use Flourish\fXML;

View::cache( true );

echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
?>
<collection
	xmlns="http://www.cccbr.org.uk/methods/schemas/2007/05/methods"
	xmlns:opensearch="http://a9.com/-/spec/opensearch/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	date="<?= date( 'Y-m-d' )?>">
	<collectionName><?= fXML::encode( 'Search results for: '.$this->get( 'queryString' ) )?></collectionName>
	<notes>Generated by Blueline using CCBR data</notes>
	<atom:link rel="search" type="application/opensearchdescription+xml" href="<?=$this->get( 'site[baseURL]' )?>/services/opensearch/methods.xml" />
	<opensearch:Query role="request" searchTerms="<?=$this->encode( 'q' )?>" />
	<opensearch:totalResults><?= fXML::encode( $this->get( 'count' ) )?></opensearch:totalResults>
	<opensearch:startIndex><?= fXML::encode( $this->get( 'limit[current]' ) )?></opensearch:startIndex>
	<methodSet>
<?php foreach( $this->get( 'methods' ) as $method ) : ?>
		<method>
			<stage><?= fXML::encode( $method->stage() )?></stage>
			<notation><?= fXML::encode( $method->notation() )?></notation>
			<title><?= fXML::encode( $method->title() )?></title>
			<classification><?= fXML::encode( $method->classification() )?></classification>
		</method>
<?php endforeach; ?>
	</methodSet>
</collection>
