<?php
namespace Blueline;
echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
?>
<collection xmlns="http://www.cccbr.org.uk/methods/schemas/2007/05/methods" date="<?php echo date( 'Y-m-d' ); ?>">
	<collectionName><?php echo htmlspecialchars( \Helpers\Text::toList( array_map( function( $m ){ return $m->title(); }, $methods ) ) ); ?></collectionName>
	<notes>Generated by Blueline using CCBR data</notes>
	<methodSet>
<?php foreach( $methods as $method ) : ?>
		<method>
			<stage><?php echo $method->stage(); ?></stage>
			<notation><?php echo $method->notation(); ?></notation>
			<title><?php echo $method->title(); ?></title>
			<classification><?php echo $method->classification(); ?></classification>
<?php if( $method->lengthOfLead() ) : ?>
			<lengthOfLead><?php echo $method->lengthOfLead(); ?></lengthOfLead>
<?php endif; ?>
<?php if( $method->numberOfHunts() ) : ?>
			<numberOfHunts><?php echo $method->numberOfHunts(); ?></numberOfHunts>
<?php endif; ?>
<?php if( $method->palindromic() || $method->doubleSym() || $method->rotational() ) : ?>
			<symmetry><?php echo trim( ($method->palindromic()?'palindromic ':'').($method->doubleSym()?'double ':'').($method->rotational()?'rotational ':'') ); ?></symmetry>
<?php endif; ?>
<?php if( $method->leadHead() ) : ?>
			<leadHead><?php echo $method->leadHead(); ?></leadHead>
<?php endif; ?>
<?php if( $method->leadHeadCode() ) : ?>
			<leadHeadCode><?php echo $method->leadHeadCode(); ?></leadHeadCode>
<?php endif; ?>
<?php if( $method->fchGroups() ) : ?>
			<falseness><fchGroups><?php echo $method->fchGroups(); ?></fchGroups></falseness>
<?php endif; ?>
<?php if( $method->rwRef() || $method->bnRef() || $method->tdmmRef() || $method->pmmRef() ) : ?>
			<references>
<?php if( $method->rwRef() ) : ?>
				<rwRef><?php echo $method->rwRef(); ?></rwRef>
<?php endif; ?>
<?php if( $method->bnRef() ) : ?>
				<bnRef><?php echo $method->bnRef(); ?></bnRef>
<?php endif; ?>
<?php if( $method->tdmmRef() ) : ?>
				<tdmmRef><?php echo $method->tdmmRef(); ?></tdmmRef>
<?php endif; ?>
<?php if( $method->pmmRef() ) : ?>
				<pmmRef><?php echo $method->pmmRef(); ?></pmmRef>
<?php endif; ?>
			</references>
<?php endif; ?>
<?php if( $method->firstHandbellPeal_date() || $method->firstTowerbellPeal_date() ) : ?>
			<performances>
<?php if( $method->firstHandbellPeal_date() ) : ?>
				<firstHandbellPeal><date><?php echo $method->firstHandbellPeal_date(); ?></date></firstHandbellPeal>
<?php endif; ?>
<?php if( $method->firstTowerbellPeal_date() ) : ?>
				<firstTowerbellPeal><date><?php echo $method->firstTowerbellPeal_date(); ?></date><location><?php echo $method->firstTowerbellPeal_location(); ?></location></firstTowerbellPeal>
<?php endif; ?>
			</performances>
<?php endif; ?>
		</method>
<?php endforeach; ?>
	</methodSet>
</collection>
