(function(window,document,undefined){
function h(a){return function(){return this[a]}}var i;function j(a,b){var c=arguments.length>2?Array.prototype.slice.call(arguments,2):[];return function(){c.push.apply(c,arguments);return b.apply(a,c)}};function l(a,b){this.l=a;this.a=b}l.prototype.createElement=function(a,b,c){a=this.l.createElement(a);if(b)for(var d in b)if(b.hasOwnProperty(d))if(d=="style"&&this.a.getName()=="MSIE")a.style.cssText=b[d];else a.setAttribute(d,b[d]);c&&a.appendChild(this.l.createTextNode(c));return a};function m(a,b,c){a=a.l.getElementsByTagName(b)[0];if(!a)a=document.documentElement;if(a&&a.lastChild){a.insertBefore(c,a.lastChild);return true}return false}
function n(a,b){if(b.parentNode){b.parentNode.removeChild(b);return true}return false}function o(a,b,c){a=b.className.split(/\s+/);for(var d=0,e=a.length;d<e;d++)if(a[d]==c)return;a.push(c);b.className=a.join(" ").replace(/^\s+/,"")}function p(a,b,c){a=b.className.split(/\s+/);for(var d=[],e=0,f=a.length;e<f;e++)a[e]!=c&&d.push(a[e]);b.className=d.join(" ").replace(/^\s+/,"").replace(/\s+$/,"")}
function s(a,b,c){a=b.className.split(/\s+/);b=0;for(var d=a.length;b<d;b++)if(a[b]==c)return true;return false};function t(a,b,c,d,e,f,g,k){this.fa=a;this.la=b;this.Q=c;this.P=d;this.ia=e;this.ha=f;this.O=g;this.ma=k}i=t.prototype;i.getName=h("fa");i.$=h("la");i.W=h("Q");i.X=h("P");i.Y=h("ia");i.Z=h("ha");i.V=h("O");i.o=h("ma");function u(a,b){this.a=a;this.g=b}var v=new t("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",undefined,false);u.prototype.parse=function(){return this.a.indexOf("MSIE")!=-1?x(this):this.a.indexOf("Opera")!=-1?y(this):this.a.indexOf("AppleWebKit")!=-1?A(this):this.a.indexOf("Gecko")!=-1?B(this):v};
function C(a){var b=D(a,a.a,/(iPod|iPad|iPhone|Android)/,1);if(b!="")return b;a=D(a,a.a,/(Linux|Mac_PowerPC|Macintosh|Windows)/,1);if(a!=""){if(a=="Mac_PowerPC")a="Macintosh";return a}return"Unknown"}function F(a){var b=D(a,a.a,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b)return b;if(b=D(a,a.a,/(iPhone )?OS ([\d_]+)/,2))return b;if(a=D(a,a.a,/Linux ([i\d]+)/,1))return a;return"Unknown"}
function x(a){var b=D(a,a.a,/(MSIE [\d\w\.]+)/,1);if(b!=""){var c=b.split(" ");b=c[0];c=c[1];return new t(b,c,b,c,C(a),F(a),G(a,a.g),H(a,c)>=6)}return new t("MSIE","Unknown","MSIE","Unknown",C(a),F(a),G(a,a.g),false)}
function y(a){var b="Unknown",c="Unknown",d=D(a,a.a,/(Presto\/[\d\w\.]+)/,1);if(d!=""){c=d.split("/");b=c[0];c=c[1]}else{if(a.a.indexOf("Gecko")!=-1)b="Gecko";d=D(a,a.a,/rv:([^\)]+)/,1);if(d!="")c=d}if(a.a.indexOf("Version/")!=-1){d=D(a,a.a,/Version\/([\d\.]+)/,1);if(d!="")return new t("Opera",d,b,c,C(a),F(a),G(a,a.g),H(a,d)>=10)}d=D(a,a.a,/Opera[\/ ]([\d\.]+)/,1);if(d!="")return new t("Opera",d,b,c,C(a),F(a),G(a,a.g),H(a,d)>=10);return new t("Opera","Unknown",b,c,C(a),F(a),G(a,a.g),false)}
function A(a){var b=C(a),c=F(a),d=D(a,a.a,/AppleWebKit\/([\d\.\+]+)/,1);if(d=="")d="Unknown";var e="Unknown";if(a.a.indexOf("Chrome")!=-1)e="Chrome";else if(a.a.indexOf("Safari")!=-1)e="Safari";else if(a.a.indexOf("AdobeAIR")!=-1)e="AdobeAIR";var f="Unknown";if(a.a.indexOf("Version/")!=-1)f=D(a,a.a,/Version\/([\d\.\w]+)/,1);else if(e=="Chrome")f=D(a,a.a,/Chrome\/([\d\.]+)/,1);else if(e=="AdobeAIR")f=D(a,a.a,/AdobeAIR\/([\d\.]+)/,1);var g=false;if(e=="AdobeAIR"){g=D(a,f,/\d+\.(\d+)/,1);g=H(a,f)>2||
H(a,f)==2&&parseInt(g,10)>=5}else{g=D(a,d,/\d+\.(\d+)/,1);g=H(a,d)>=526||H(a,d)>=525&&parseInt(g,10)>=13}return new t(e,f,"AppleWebKit",d,b,c,G(a,a.g),g)}
function B(a){var b="Unknown",c="Unknown",d=false;if(a.a.indexOf("Firefox")!=-1){b="Firefox";var e=D(a,a.a,/Firefox\/([\d\w\.]+)/,1);if(e!=""){d=D(a,e,/\d+\.(\d+)/,1);c=e;d=e!=""&&H(a,e)>=3&&parseInt(d,10)>=5}}else if(a.a.indexOf("Mozilla")!=-1)b="Mozilla";e=D(a,a.a,/rv:([^\)]+)/,1);if(e=="")e="Unknown";else if(!d){d=H(a,e);var f=parseInt(D(a,e,/\d+\.(\d+)/,1),10),g=parseInt(D(a,e,/\d+\.\d+\.(\d+)/,1),10);d=d>1||d==1&&f>9||d==1&&f==9&&g>=2||e.match(/1\.9\.1b[123]/)!=null||e.match(/1\.9\.1\.[\d\.]+/)!=
null}return new t(b,c,"Gecko",e,C(a),F(a),G(a,a.g),d)}function H(a,b){a=D(a,b,/(\d+)/,1);if(a!="")return parseInt(a,10);return-1}function D(a,b,c,d){if((a=b.match(c))&&a[d])return a[d];return""}function G(a,b){if(b.documentMode)return b.documentMode};function I(a,b,c,d){this.b=a;this.c=b;this.s=c;this.f=d||J;this.e=new K("-")}var J="wf";function L(a){o(a.b,a.c,a.e.d(a.f,"loading"));M(a,"loading")}function N(a){p(a.b,a.c,a.e.d(a.f,"loading"));s(a.b,a.c,a.e.d(a.f,"active"))||o(a.b,a.c,a.e.d(a.f,"inactive"));M(a,"inactive")}function aa(a){p(a.b,a.c,a.e.d(a.f,"loading"));p(a.b,a.c,a.e.d(a.f,"inactive"));o(a.b,a.c,a.e.d(a.f,"active"));M(a,"active")}function M(a,b,c,d){a.s[b]&&a.s[b](c,d)};function ba(){this.F={}}function ca(a,b){var c=[];for(var d in b)if(b.hasOwnProperty(d)){var e=a.F[d];e&&c.push(e(b[d]))}return c};function O(a,b,c,d,e){this.b=a;this.i=b;this.j=c;this.h=d;this.m=e;this.v=0;this.M=this.D=false}O.prototype.watch=function(a,b,c,d){for(var e=a.length,f=0;f<e;f++){var g=a[f];b[g]||(b[g]=["n4"]);this.v+=b[g].length}if(d)this.D=d;for(f=0;f<e;f++){g=a[f];d=b[g];for(var k=c[g],q=0,E=d.length;q<E;q++){var w=d[q],r=this.i,z=g;o(r.b,r.c,r.e.d(r.f,z,w,"loading"));M(r,"fontloading",z,w);r=j(this,this.R);z=j(this,this.S);new P(r,z,this.b,this.j,this.h,this.m,g,w,k)}}};
O.prototype.R=function(a,b){var c=this.i;p(c.b,c.c,c.e.d(c.f,a,b,"loading"));p(c.b,c.c,c.e.d(c.f,a,b,"inactive"));o(c.b,c.c,c.e.d(c.f,a,b,"active"));M(c,"fontactive",a,b);this.M=true;Q(this)};O.prototype.S=function(a,b){var c=this.i;p(c.b,c.c,c.e.d(c.f,a,b,"loading"));s(c.b,c.c,c.e.d(c.f,a,b,"active"))||o(c.b,c.c,c.e.d(c.f,a,b,"inactive"));M(c,"fontinactive",a,b);Q(this)};function Q(a){if(--a.v==0&&a.D)a.M?aa(a.i):N(a.i)};function P(a,b,c,d,e,f,g,k,q){this.N=a;this.aa=b;this.b=c;this.j=d;this.h=e;this.m=f;this.ea=new R;this.U=new S;this.z=g;this.w=k;this.T=q||da;this.G=T(this,U);this.H=T(this,V);this.B=this.G;this.C=this.H;this.K=W(this,U);this.L=W(this,V);this.ka=f();this.t()}var U="arial,'URW Gothic L',sans-serif",V="Georgia,'Century Schoolbook L',serif",da="BESs";
P.prototype.t=function(){var a=this.j.n(this.K),b=this.j.n(this.L);if((this.G!=a||this.H!=b)&&this.B==a&&this.C==b)X(this,this.N);else if(this.m()-this.ka>=5E3)X(this,this.aa);else{this.B=a;this.C=b;ea(this)}};function ea(a){a.h(function(b,c){return function(){c.call(b)}}(a,a.t),25)}function X(a,b){n(a.b,a.K);n(a.b,a.L);b(a.z,a.w)}function T(a,b){b=W(a,b,true);var c=a.j.n(b);n(a.b,b);return c}
function W(a,b,c){var d=a.U.expand(a.w);b=a.b.createElement("span",{style:"position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;font-family:"+(c?"":a.ea.quote(a.z)+",")+b+";"+d},a.T);m(a.b,"body",b);return b};function Y(a,b,c,d,e){this.b=a;this.A=b;this.c=c;this.h=d;this.a=e;this.p=this.q=0}Y.prototype.r=function(a,b){this.A.F[a]=b};Y.prototype.load=function(a){var b=new I(this.b,this.c,a);this.a.o()?fa(this,b,a):N(b)};Y.prototype.ca=function(a,b,c,d){if(d)a.load(j(this,this.ga,b,c));else{a=--this.q==0;this.p--;if(a)this.p==0?N(b):L(b);c.watch([],{},{},a)}};Y.prototype.ga=function(a,b,c,d,e){var f=--this.q==0;f&&L(a);this.h(j(this,function(g,k,q,E,w){g.watch(k,q||{},E||{},w)},b,c,d,e,f))};
function fa(a,b,c){c=ca(a.A,c);a.p=a.q=c.length;for(var d=new O(a.b,b,{n:function(k){return k.offsetWidth}},a.h,function(){return(new Date).getTime()}),e=0,f=c.length;e<f;e++){var g=c[e];ga(g,a.a,j(a,a.ca,g,b,d))}};function K(a){this.da=a||ha}var ha="-";K.prototype.d=function(){for(var a=[],b=0;b<arguments.length;b++)a.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return a.join(this.da)};function R(){this.J="'"}R.prototype.quote=function(a){var b=[];a=a.split(/,\s*/);for(var c=0;c<a.length;c++){var d=a[c].replace(/['"]/g,"");d.indexOf(" ")==-1?b.push(d):b.push(this.J+d+this.J)}return b.join(",")};function S(){this.I=ia;this.k=ja}var ia=["font-style","font-weight"],ja={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};function Z(a,b,c){this.ba=a;this.ja=b;this.k=c}Z.prototype.expand=function(a,b){for(var c=0;c<this.k.length;c++)if(b==this.k[c][0]){a[this.ba]=this.ja+":"+this.k[c][1];return}};
S.prototype.expand=function(a){if(a.length!=2)return null;for(var b=[null,null],c=0,d=this.I.length;c<d;c++){var e=this.I[c],f=a.substr(c,1);(new Z(c,e,this.k[e])).expand(b,f)}return b[0]&&b[1]?b.join(";")+";":null};window.WebFont=function(){var a=(new u(navigator.userAgent,document)).parse();return new Y(new l(document,a),new ba,document.documentElement,function(b,c){setTimeout(b,c)},a)}();window.WebFont.load=window.WebFont.load;window.WebFont.addModule=window.WebFont.r;t.prototype.getName=t.prototype.getName;t.prototype.getVersion=t.prototype.$;t.prototype.getEngine=t.prototype.W;t.prototype.getEngineVersion=t.prototype.X;t.prototype.getPlatform=t.prototype.Y;t.prototype.getPlatformVersion=t.prototype.Z;
t.prototype.getDocumentMode=t.prototype.V;t.prototype.isSupportingWebFont=t.prototype.o;function $(a,b){this.b=a;this.u=b}$.prototype.load=function(a){for(var b=this.u.urls||[],c=this.u.families||[],d=0,e=b.length;d<e;d++)m(this.b,"head",this.b.createElement("link",{rel:"stylesheet",href:b[d]}));a(c)};function ga(a,b,c){return c(b.o())}window.WebFont.r("custom",function(a){var b=(new u(navigator.userAgent,document)).parse();return new $(new l(document,b),a)});window.WebFontConfig&&window.WebFont.load(window.WebFontConfig);

define( {
	load: function( name, req, load, config ) {
		if( config.isBuild ) {
			load( null );
		}
		else {
			window.WebFont.load( {
				custom: {
					families: [name],
					urls: ['/css/default.css']
				},
				active: function() { load( true ); },
				inactive: function() { load( false ); }
			} );
		}
	}
} );
})(window,document);
