#!/bin/bash

dWhich=`which "$0"`
d=`dirname "$dWhich"`

echo "Downloading new method data..."
curl --progress-bar -o "$d/data/allmeths-xml.zip" "http://methods.org.uk/method-collections/xml-zip-files/allmeths-xml.zip"
echo -n "Unzipping..."
unzip -u -d "$d/data" -o "$d/data/allmeths-xml.zip"
echo "Done"

echo -n "Creating SQL..."
php "$d/xml2sql.php" > "$d/methods.sql"
echo "Done"
echo -n "Compressing SQL..."
gzip -9f "$d/methods.sql"
echo "Done"

echo -e "\nCompleted file at: $d/methods.sql.gz\n"
