Blueline_welcome:
    path: /
    defaults: { _controller: BluelinePagesBundle:Pages:page, page: 'welcome' }

Blueline_Pages_view:
    path: /{page}.{_format}
    defaults: { _controller: BluelinePagesBundle:Pages:page, _format: 'html' }
    requirements:
        page:    about
        _format: html

Blueline_Pages_copyright:
    path: /copyright
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /about
        permanent: true