Blueline_welcome:
    pattern:  /
    defaults: { _controller: BluelinePagesBundle:Pages:page, page: 'welcome' }

Blueline_Pages_view:
    pattern:  /{page}.{_format}
    defaults: { _controller: BluelinePagesBundle:Pages:page, _format: 'html' }
    requirements:
        page:    about|copyright
        _format: html
