#!/bin/bash

dWhich=`which "$0"`
d=`dirname "$dWhich"`

echo "towers.sql:"

# Remove old files
rm -f "$d/towers.sql"
rm -f "$d/towers.sql.gz"

# Download data
echo "Downloading data"
curl --progress-bar --referer "http://dove.cccbr.org.uk" --user-agent "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10" -o "$d/data/dove.txt" "http://dove.cccbr.org.uk/downloads.php?download=dove.txt"
curl --progress-bar --referer "http://dove.cccbr.org.uk" --user-agent "Mozilla/5.0 (X11; U; Linux x86_64; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.224 Safari/534.10" -o "$d/data/newpks.txt" "http://dove.cccbr.org.uk/downloads.php?download=newpks.txt"

# Create SQL
echo -n "Parsing data"
php "$d/txt2sql.php" > "$d/towers.sql"
echo "Done"

# gzip only if no error
if [ "`tail -n 1 "$d/towers.sql"`" = "-- End" ]; then
	gzip -9c "$d/towers.sql" > "$d/towers.sql.gz"
fi
