Blueline_Towers_welcome:
    pattern:  /
    defaults: { _controller: BluelineTowersBundle:Towers:welcome }


Blueline_Towers_view_redirect:
    path: /view
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: Blueline_Towers_welcome
        permanent: true
Blueline_Towers_view_redirect2:
    path: /view/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: Blueline_Towers_welcome
        permanent: true

Blueline_Towers_view:
    pattern: /view/{id}.{_format}
    defaults: { _controller: BluelineTowersBundle:Towers:view, _format: html }
    requirements:
        id: ^(?(?=.*\.(html|txt|json|xml)$).*(?=\.)|.*$)
        _format: html|txt|json

Blueline_Towers_search:
    pattern:  /search.{_format}
    defaults: { _controller: BluelineTowersBundle:Towers:search, _format: html }
    requirements:
        _format: html|txt|json|atom

Blueline_Towers_sitemap:
    pattern:  /sitemap.{_format}
    defaults: { _controller: BluelineTowersBundle:Towers:sitemap }
    requirements:
        _format: xml
