Blueline\TowersBundle\Entity\Tower:
    properties:
        latitude:
            - GreaterThanOrEqual:
                value: -90
            - LessThanOrEqual:
                value: 90
        longitude:
            - GreaterThanOrEqual:
                value: -180
            - LessThanOrEqual:
                value: 180
        latitudeSatNav:
            - GreaterThanOrEqual:
                value: -90
            - LessThanOrEqual:
                value: 90
        longitudeSatNav:
            - GreaterThanOrEqual:
                value: -180
            - LessThanOrEqual:
                value: 180
        note:
            - Regex: "/^[A-G]{1}[#b]?$/"
        practiceNight:
            - GreaterThanOrEqual:
                value: 1
            - LessThanOrEqual:
                value: 7
        practiceStart:
            - Regex: "/^\d\d:\d\d$/"
        webPage:
            - Url: ~
