Blueline_welcome:
    pattern:  /
    defaults: { _controller: BluelineCCCBRDataBundle:Pages:page, page: 'welcome' }


Blueline_page:
    pattern:  /{page}.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Pages:page, _format: html }
    requirements:
        page: about|copyright|debug|robots|humans|site|sitemap|sitemap_root
        _format: html|txt|xml|manifest


Blueline_Methods_welcome:
    pattern:  /methods
    defaults: { _controller: BluelineCCCBRDataBundle:Methods:welcome }

Blueline_Methods_view:
    pattern: /methods/view/{title}.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Methods:view, _format: html }
    requirements:
        title: ^(?(?=.*\.(html|txt|json|xml)$).*(?=\.)|.*$)
        _format: html|txt|json|xml

Blueline_Methods_search:
    pattern:  /methods/search.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Methods:search, _format: html }
    requirements:
        _format: html|txt|json|atom
        
Blueline_Methods_sitemap:
    pattern:  /methods/sitemap.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Methods:sitemap }
    requirements:
        _format: xml


Blueline_Associations_welcome:
    pattern:  /associations
    defaults: { _controller: BluelineCCCBRDataBundle:Associations:welcome }

Blueline_Associations_view:
    pattern: /associations/view/{abbreviation}.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Associations:view, _format: html }
    requirements:
        _format: html|txt|json

Blueline_Associations_search:
    pattern:  /associations/search.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Associations:search, _format: html }
    requirements:
        _format: html|txt|json|atom
        
Blueline_Associations_sitemap:
    pattern:  /associations/sitemap.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Associations:sitemap }
    requirements:
        _format: xml


Blueline_Towers_welcome:
    pattern:  /towers
    defaults: { _controller: BluelineCCCBRDataBundle:Towers:welcome }

Blueline_Towers_view:
    pattern: /towers/view/{doveid}.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Towers:view, _format: html }
    requirements:
        _format: html|txt|json

Blueline_Towers_search:
    pattern:  /towers/search.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Towers:search, _format: html }
    requirements:
        _format: html|txt|json|atom
        
Blueline_Towers_sitemap:
    pattern:  /towers/sitemap.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Towers:sitemap }
    requirements:
        _format: xml


Blueline_Opensearch_description:
    pattern:  /opensearch/{type}.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Opensearch:description }
    requirements:
        type: associations|methods|towers
        _format: xml

Blueline_Opensearch_suggestions:
    pattern:  /opensearch/suggestions/{type}.{_format}
    defaults: { _controller: BluelineCCCBRDataBundle:Opensearch:suggestions }
    requirements:
        type: associations|methods|towers
        _format: json
