Blueline_Associations_welcome:
    path: /
    defaults: { _controller: BluelineAssociationsBundle:Associations:welcome }

Blueline_Associations_view_redirect:
    path: /view
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: Blueline_Associations_welcome
        permanent: true
Blueline_Associations_view_redirect2:
    path: /view/
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: Blueline_Associations_welcome
        permanent: true

Blueline_Associations_view:
    path: /view/{id}.{_format}
    defaults: { _controller: BluelineAssociationsBundle:Associations:view, _format: html }
    requirements:
        _format: html|json

Blueline_Associations_search:
    path: /search.{_format}
    defaults: { _controller: BluelineAssociationsBundle:Associations:search, _format: html }
    requirements:
        _format: html|json

Blueline_Associations_sitemap:
    path: /sitemap.{_format}
    defaults: { _controller: BluelineAssociationsBundle:Associations:sitemap }
    requirements:
        _format: xml
