Blueline_Associations_welcome:
    pattern:  /
    defaults: { _controller: BluelineAssociationsBundle:Associations:welcome }

Blueline_Associations_view:
    pattern: /view/{id}.{_format}
    defaults: { _controller: BluelineAssociationsBundle:Associations:view, _format: html }
    requirements:
        id: ^(?(?=.*\.(html|txt|json|xml)$).*(?=\.)|.*$)
        _format: html|txt|json

Blueline_Associations_search:
    pattern:  /search.{_format}
    defaults: { _controller: BluelineAssociationsBundle:Associations:search, _format: html }
    requirements:
        _format: html|txt|json|atom

Blueline_Associations_sitemap:
    pattern:  /sitemap.{_format}
    defaults: { _controller: BluelineAssociationsBundle:Associations:sitemap }
    requirements:
        _format: xml
