version: "3"

services:
  # Main container
  php:
    # Uncomment the next line to use a non-root user for all processes.
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    # user: vscode

    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update VARIANT to pick a PHP version: 8, 7, 7.4, 7.3
        VARIANT: "8"
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached

    ports:
        - 8000:8000

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  # Database image
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: blueline

volumes:
  postgres-data:
