services:
  blueline:
    user: vscode
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity # Overrides default command so things don't shut down after the process ends.

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data when container shuts down
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: blueline
      TZ: Europe/London
      PGTZ: Europe/London
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d blueline"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
