<?php

namespace Blueline\MethodsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerformanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceRepository extends EntityRepository
{
    public function findByRungUrl($url)
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT p, m FROM BluelineMethodsBundle:Performance p
             LEFT JOIN p.method m
             WHERE p.type = \'renamedMethod\' AND p.rung_url = :url'
        )->setParameter('url', $url);

        try {
            $result = $query->getSingleResult();
            return $result->getMethod()->getUrl();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
