<?php

namespace Blueline\MethodsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PerformanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerformanceRepository extends EntityRepository
{
}
