Blueline\AssociationsBundle\Entity\Association:
    type: entity
    repositoryClass: Blueline\AssociationsBundle\Entity\AssociationRepository
    table: associations
    id:
        id:
            type: string
            length: 8
    fields:
        name:
            type: string
            length: 255
            unique: true
        link:
            type: text
        outline:
            type: json_array
            nullable: true
    manyToMany:
        towers:
            targetEntity: Blueline\TowersBundle\Entity\Tower
            mappedBy: associations
