Blueline\TowersBundle\Entity\Tower:
    type: entity
    repositoryClass: Blueline\TowersBundle\Entity\TowerRepository
    table: towers
    id:
        id:
            type: string
            length: 10
    fields:
        gridReference:
            type: string
            length: 10
            nullable: true
        latitude:
            type: decimal
            precision: 8
            scale: 5
            nullable: true
        longitude:
            type: decimal
            precision: 8
            scale: 5
            nullable: true
        latitudeSatNav:
            type: decimal
            precision: 8
            scale: 5
            nullable: true
        longitudeSatNav:
            type: decimal
            precision: 8
            scale: 5
            nullable: true
        postcode:
            type: string
            length: 10
            nullable: true
        country:
            type: string
            length: 255
        county:
            type: string
            length: 255
            nullable: true
        diocese:
            type: string
            length: 255
        place:
            type: string
            length: 255
        altName:
            type: string
            length: 255
            nullable: true
        dedication:
            type: string
            length: 255
        bells:
            type: smallint
        weight:
            type: smallint
        weightApprox:
            type: boolean
        note:
            type: string
            length: 2
            nullable: true
        hz:
            type: decimal
            precision: 5
            scale: 1
            nullable: true
        practiceNight:
            type: smallint
            nullable: true
        practiceStart:
            type: string
            length: 5
            nullable: true
        practiceNotes:
            type: text
            nullable: true
        groundFloor:
            type: boolean
        toilet:
            type: boolean
        unringable:
            type: boolean
        simulator:
            type: boolean
        overhaulYear:
            type: smallint
            nullable: true
        contractor:
            type: string
            length: 255
            nullable: true
        tunedYear:
            type: smallint
            nullable: true
        extraInfo:
            type: text
            nullable: true
        webPage:
            type: text
            nullable: true
    oneToMany:
        oldpks:
            targetEntity: OldPK
            mappedBy: tower
        performances:
            targetEntity: Blueline\MethodsBundle\Entity\Performance
            mappedBy: location_tower
    manyToMany:
        associations:
            targetEntity: Blueline\AssociationsBundle\Entity\Association
            inversedBy: towers
            joinTable:
                name: towers_associations
                joinColumns:
                    tower_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    association_id:
                        referencedColumnName: id
