#!/bin/bash

# Removes files that are unnecessary for production from the source tree

cd ../../
rm -rf docs
rm -rf tests
rm -rf utilities
rm -rf .git
rm .gitignore
rm ./libraries/parsecsv.lib.php
rm ./libraries/phpcoord.php
