Blueline\Entity\MethodSimilarity:
    type: entity
    table: methods_similar
    id:
        method1:
            associationKey: true
        method2:
            associationKey: true
    fields:
        similarity:
            type: float
            nullable: true
        onlyDifferentOverLeadEnd:
            type: boolean
            nullable: true
        onlyDifferentOverHalfLead:
            type: boolean
            nullable: true
        onlyDifferentOverLeadEndAndHalfLead:
            type: boolean
            nullable: true
    manyToOne:
        method1:
            targetEntity: Method
            inversedBy: methodsimilarity1
            joinColumn:
                name: method1_title
                referencedColumnName: title
        method2:
            targetEntity: Method
            inversedBy: methodsimilarity2
            joinColumn:
                name: method2_title
                referencedColumnName: title
