<?php
namespace Blueline;
use Pan\View;

View::cache( true );

echo "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n";
?>
<collection xmlns="http://www.cccbr.org.uk/methods/schemas/2007/05/methods" date="<?= date( 'Y-m-d' )?>">
	<collectionName><?php echo htmlspecialchars( \Helpers\Text::toList( array_map( function( $m ){ return $m->title(); }, $this->get( 'methods', array() ) ) ) ); ?></collectionName>
	<notes>Generated by Blueline using CCBR data</notes>
	<methodSet>
<?php foreach( $this->get( 'methods', array() ) as $method ) : ?>
		<method>
			<stage><?php=$method->stage()?></stage>
			<notation><?=$method->notation()?></notation>
			<title><?=$method->title()?></title>
			<classification><?=$method->classification()?></classification>
<?php if( $method->lengthOfLead() ) : ?>
			<lengthOfLead><?=$method->lengthOfLead()?></lengthOfLead>
<?php endif; ?>
<?php if( $method->numberOfHunts() ) : ?>
			<numberOfHunts><?=$method->numberOfHunts()?></numberOfHunts>
<?php endif; ?>
<?php if( $method->palindromic() || $method->doubleSym() || $method->rotational() ) : ?>
			<symmetry><?= trim( ($method->palindromic()?'palindromic ':'').($method->doubleSym()?'double ':'').($method->rotational()?'rotational ':'') )?></symmetry>
<?php endif; ?>
<?php if( $method->leadHead() ) : ?>
			<leadHead><?=$method->leadHead()?></leadHead>
<?php endif; ?>
<?php if( $method->leadHeadCode() ) : ?>
			<leadHeadCode><?=$method->leadHeadCode()?></leadHeadCode>
<?php endif; ?>
<?php if( $method->fchGroups() ) : ?>
			<falseness><fchGroups><?$method->fchGroups()?></fchGroups></falseness>
<?php endif; ?>
<?php if( $method->rwRef() || $method->bnRef() || $method->tdmmRef() || $method->pmmRef() ) : ?>
			<references>
<?php if( $method->rwRef() ) : ?>
				<rwRef><?=$method->rwRef()?></rwRef>
<?php endif; ?>
<?php if( $method->bnRef() ) : ?>
				<bnRef><?=$method->bnRef()?></bnRef>
<?php endif; ?>
<?php if( $method->tdmmRef() ) : ?>
				<tdmmRef><?=$method->tdmmRef()?></tdmmRef>
<?php endif; ?>
<?php if( $method->pmmRef() ) : ?>
				<pmmRef><?=$method->pmmRef()?></pmmRef>
<?php endif; ?>
			</references>
<?php endif; ?>
<?php if( $method->firstHandbellPeal_date() || $method->firstTowerbellPeal_date() ) : ?>
			<performances>
<?php if( $method->firstHandbellPeal_date() ) : ?>
				<firstHandbellPeal><date><?=$method->firstHandbellPeal_date()?></date></firstHandbellPeal>
<?php endif; ?>
<?php if( $method->firstTowerbellPeal_date() ) : ?>
				<firstTowerbellPeal><date><?=$method->firstTowerbellPeal_date()?></date><location><?=$method->firstTowerbellPeal_location()?></location></firstTowerbellPeal>
<?php endif; ?>
			</performances>
<?php endif; ?>
		</method>
<?php endforeach; ?>
	</methodSet>
</collection>
