Blueline_Services_oembed:
    path:     /oembed.{_format}
    defaults: { _controller: BluelineServicesBundle:Oembed:index }
    requirements:
        _format: json|xml

Blueline_FontPreview:
    path:     /previewFont.{_format}
    defaults: { _controller: BluelineServicesBundle:FontPreview:preview }
    requirements:
        _format: png