Blueline_Services_oembed:
    path: /oembed.{_format}
    defaults: { _controller: BluelineServicesBundle:Oembed:index }
    requirements:
        _format: json|xml

Blueline_Notation_expand:
    path: /notation.{_format}
    defaults: { _controller: BluelineServicesBundle:Notation:parse }
    requirements:
        _format: txt|json

Blueline_Services_siril:
    path: /siril
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: 'https://bobwallis.github.io/CompositionProver/'
        permanent: true

Blueline_Services_siril_why:
    path: /siril/about
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: 'https://bobwallis.github.io/CompositionProver/'
        permanent: true
